export const SUPPORTED_LOCALES = [
  { code: "en", label: "English", shortLabel: "EN" },
  { code: "hi", label: "हिन्दी", shortLabel: "हि" },
  { code: "te", label: "తెలుగు", shortLabel: "తె" },
];

export const DEFAULT_LOCALE = "en";

const UI_MESSAGES = {
  en: {
    language: "Language",
    chooseLanguage: "Choose language",
    dashboard: "Dashboard",
    aiHoloTutor: "AI Holo Tutor",
    principalControl: "Principal Control",
    students: "Students",
    classes: "Classes",
    mockTests: "Mock Tests",
    batchExams: "Batch Exams",
    resources: "Notes & Tests",
    progress: "Progress",
    parents: "Parents",
    syllabus: "Syllabus",
    settings: "Settings",
    instituteLogin: "Institute login",
    openDemo: "Open demo workspace",
    backToWebsite: "Back to website",
    signIn: "Sign in to workspace",
    courseLibrary: "Course library",
    chooseExam: "Choose an entrance exam",
    printComplete: "Print complete paper",
    savePdf: "Save complete paper as PDF",
    set: "Set",
    secureExamSets: "Secure exam sets",
    chooseExamSet: "Choose a paper set",
    uniqueOrder: "Unique order",
    sameValidatedPaper: "Same validated paper",
    examSetAssurance: "All questions, marks, sections, and syllabus coverage stay identical. Only question and option order changes.",
    questionsShuffled: "Questions shuffled",
    optionsShuffled: "Options shuffled",
    answersRemapped: "Answer key remapped",
    printSetHelp: "Select the booklet code you want to print for this test.",
    saveSetHelp: "Select a booklet code, then choose Save as PDF in the browser print window.",
    printSet: "Print Set {set}",
    saveSetPdf: "Save Set {set} as PDF",
    closeExamSetDialog: "Close paper set selector",
    cancel: "Cancel",
    backToLibrary: "Back to library",
    submitTest: "Submit test",
    previous: "Previous",
    next: "Next",
    bookmark: "Bookmark",
    bookmarked: "Bookmarked",
    question: "Question",
    answered: "answered",
    easy: "Easy",
    medium: "Medium",
    challenging: "Challenging",
    fullTest: "Full Test",
    questions: "questions",
    marks: "marks",
    minutes: "minutes",
    syllabusSkill: "Syllabus skill",
    answer: "Answer",
    explanation: "Explanation",
    candidateName: "Candidate name",
    rollNumber: "Roll number",
    bookletCode: "Booklet code",
    instructions: "Instructions",
    responseSheet: "Response sheet",
    testSummary: "Test summary",
    subject: "Subject",
    range: "Question range",
    qualifying: "Qualifying standard",
    practiceEdition: "Practice edition",
    candidateSignature: "Candidate signature",
    invigilatorSignature: "Invigilator signature",
    date: "Date",
    none: "None",
    negativeMarking: "Negative marking",
    marksEach: "Marks each",
    duration: "Duration",
    section: "Section",
    practiceNotice: "Practice material prepared to the stated paper pattern; this is not an official examination booklet.",
    responseSheetHelp: "Fill one circle per question.",
    retainedLanguage: "This language-subject question remains in English to preserve its grammar and answer validity.",
    demoNotice: "Demo workspace is available while secure MongoDB and email OTP services are being configured.",
    continueDemo: "Continue to demo workspace",
    welcomeBack: "Welcome back.",
    welcomeCopy: "Use your verified Vijetha account or continue to the public demo workspace.",
    secureWorkspace: "Secure institute workspace",
    email: "Email",
    password: "Password",
    signInSecurely: "Sign in securely",
    forgotPassword: "Forgot password?",
    createAccount: "Create account",
    securityNotice: "Passwords and OTP codes are never stored as readable text.",
    newFullPracticeTests: "{count} new full practice tests",
    levelSummary: "10 Easy · 10 Medium · 10 Challenging · Testing database",
    closeTestStudio: "Close test studio",
    loadingDatabase: "Loading the Testing database",
    readingQuestionModule: "Reading the syllabus-aligned {course} question module.",
    loadingFullTest: "Loading {course} full test",
    validatingQuestions: "Validating all {count} questions before opening the runner.",
    printSettings: "Print settings: All pages · Portrait · Default scale. Turn off browser headers and footers for the cleanest paper.",
    attempted: "Attempted",
    notAttempted: "Not attempted",
    current: "Current",
    readingPassage: "Reading passage",
    evsStudyNotes: "EVS study notes",
    fullTestModule: "Full-test question module",
    paperContains: "Every paper contains newly authored questions:",
    testsShown: "full tests shown",
    allLevels: "All levels",
    filterDifficulty: "Filter tests by difficulty",
    printTestList: "Print test list",
    test: "Test",
    topics: "topics",
    closeTest: "Close test",
    preparingPaper: "Preparing complete paper…",
    workspace: "Workspace",
    examBlueprint: "Exam blueprint",
    signOut: "Sign out",
    searchWorkspace: "Search workspace",
    searchAnything: "Search anything",
    goodMorning: "Good morning, {name}.",
    attentionCopy: "Here is what needs your attention across Vijetha Institute.",
    printOverview: "Print overview",
    openFullTests: "Open full tests",
    activeStudents: "Active students",
    batches: "batches",
    inPreparation: "in preparation",
    officialTopicMap: "official topic map",
    perLevel: "10 / level",
    questionsEach: "{count} questions each",
    questionRecords: "Question records",
    papers: "papers",
    syllabusAlignedBank: "syllabus-aligned bank",
    studentPulse: "Student pulse",
    progressOverview: "Progress overview",
    manageStudents: "Manage students",
    testingDatabase: "Testing database",
    fullTestLibrary: "Full-test library",
    questionsLoaded: "Questions loaded",
    structureLocked: "Syllabus structure locked",
    student: "Student",
    batch: "Batch",
    completion: "Completion",
    status: "Status",
    lastActive: "Last active",
    onTrack: "On track",
    atRisk: "At risk",
    needsReview: "Needs review",
    admissionsOpen: "Admissions are now open",
    admissionsCopy: "Sainik and Navodaya coaching from Sree Vijetha U.P School.",
    callAdmissions: "Call admissions",
    visitSchool: "Visit school website",
    admissionsBannerAlt: "Sree Vijetha Sainik and Navodaya coaching admissions banner",
  },
  hi: {
    "The paper contains 80 objective questions carrying 100 marks and must be completed in 2 hours.": "प्रश्नपत्र में 100 अंकों के 80 वस्तुनिष्ठ प्रश्न हैं और इसे 2 घंटे में पूरा करना है।",
    "Each correct response carries 1.25 marks. There is no negative marking.": "प्रत्येक सही उत्तर के 1.25 अंक हैं। ऋणात्मक अंकन नहीं है।",
    "Use the response sheet at the end and mark only one option for each question.": "अंत में दिए उत्तर पत्रक का उपयोग करें और प्रत्येक प्रश्न के लिए केवल एक विकल्प अंकित करें।",
    "The minimum qualifying marks are 14 in Section 1, 7 in Arithmetic, and 7 in Language.": "न्यूनतम अर्हता अंक खंड 1 में 14, अंकगणित में 7 और भाषा में 7 हैं।",
    "Eligible Divyang candidates receive 40 additional minutes.": "पात्र दिव्यांग अभ्यर्थियों को 40 अतिरिक्त मिनट मिलते हैं।",
    "The paper contains 125 multiple-choice questions carrying 300 marks and must be completed in 150 minutes.": "प्रश्नपत्र में 300 अंकों के 125 बहुविकल्पीय प्रश्न हैं और इसे 150 मिनट में पूरा करना है।",
    "Section A Language has 25 questions, Section B Mathematics has 50, Section C Intelligence has 25, and Section D General Knowledge has 25.": "खंड A भाषा में 25, खंड B गणित में 50, खंड C बुद्धिमत्ता में 25 और खंड D सामान्य ज्ञान में 25 प्रश्न हैं।",
    "Language, Intelligence, and General Knowledge questions carry 2 marks each; Mathematics questions carry 3 marks each.": "भाषा, बुद्धिमत्ता और सामान्य ज्ञान के प्रत्येक प्रश्न के 2 अंक तथा गणित के प्रत्येक प्रश्न के 3 अंक हैं।",
    "There is no negative marking. Mark only one answer for every question on the response sheet.": "ऋणात्मक अंकन नहीं है। उत्तर पत्रक पर प्रत्येक प्रश्न के लिए केवल एक उत्तर अंकित करें।",
    "The official qualifying standard is 25% in each subject and 40% in aggregate, subject to the applicable category rules.": "लागू श्रेणी नियमों के अधीन आधिकारिक अर्हता मानक प्रत्येक विषय में 25% और कुल मिलाकर 40% है।",
    "The Class VI practice paper contains four 50-mark sections at Class V standard.": "कक्षा VI अभ्यास प्रश्नपत्र में कक्षा V स्तर के चार 50-अंकीय खंड हैं।",
    "The response sheet follows the OMR pattern. Mark only one answer for every question.": "उत्तर पत्रक OMR प्रारूप का है। प्रत्येक प्रश्न के लिए केवल एक उत्तर अंकित करें।",
    "English is qualifying at 35% and is not counted in the written merit score.": "अंग्रेज़ी में 35% अर्हता आवश्यक है और इसके अंक लिखित मेरिट में नहीं जोड़े जाते।",
    "Intelligence Test, Mathematics, and General Knowledge & Current Affairs each require 40%.": "बुद्धिमत्ता परीक्षण, गणित और सामान्य ज्ञान एवं समसामयिकी में प्रत्येक में 40% आवश्यक हैं।",
    "The official Class VI entrance paper is bilingual in English and Hindi; this generated practice edition is in English.": "आधिकारिक कक्षा VI प्रवेश प्रश्नपत्र अंग्रेज़ी और हिन्दी में द्विभाषी है; यह अभ्यास संस्करण चुनी गई प्रदर्शन भाषा में उपलब्ध है।",
    language: "भाषा",
    chooseLanguage: "भाषा चुनें",
    dashboard: "डैशबोर्ड",
    aiHoloTutor: "AI होलो ट्यूटर",
    principalControl: "प्रधानाचार्य नियंत्रण",
    students: "विद्यार्थी",
    classes: "कक्षाएँ",
    mockTests: "मॉक टेस्ट",
    batchExams: "बैच परीक्षाएँ",
    resources: "नोट्स और टेस्ट",
    progress: "प्रगति",
    parents: "अभिभावक",
    syllabus: "पाठ्यक्रम",
    settings: "सेटिंग्स",
    instituteLogin: "संस्थान लॉगिन",
    openDemo: "डेमो कार्यक्षेत्र खोलें",
    backToWebsite: "वेबसाइट पर वापस जाएँ",
    signIn: "कार्यस्थल में साइन इन करें",
    courseLibrary: "पाठ्यक्रम पुस्तकालय",
    chooseExam: "प्रवेश परीक्षा चुनें",
    printComplete: "पूरा प्रश्नपत्र प्रिंट करें",
    savePdf: "पूरा प्रश्नपत्र PDF में सहेजें",
    set: "सेट",
    secureExamSets: "सुरक्षित परीक्षा सेट",
    chooseExamSet: "प्रश्नपत्र सेट चुनें",
    uniqueOrder: "अलग क्रम",
    sameValidatedPaper: "वही सत्यापित प्रश्नपत्र",
    examSetAssurance: "सभी प्रश्न, अंक, खंड और पाठ्यक्रम कवरेज समान रहते हैं। केवल प्रश्नों और विकल्पों का क्रम बदलता है।",
    questionsShuffled: "प्रश्नों का क्रम बदला",
    optionsShuffled: "विकल्पों का क्रम बदला",
    answersRemapped: "उत्तर कुंजी पुनः मिलाई गई",
    printSetHelp: "इस टेस्ट के लिए प्रिंट करने वाला पुस्तिका कोड चुनें।",
    saveSetHelp: "पुस्तिका कोड चुनें, फिर ब्राउज़र प्रिंट विंडो में PDF के रूप में सहेजें चुनें।",
    printSet: "सेट {set} प्रिंट करें",
    saveSetPdf: "सेट {set} PDF में सहेजें",
    closeExamSetDialog: "प्रश्नपत्र सेट चयन बंद करें",
    cancel: "रद्द करें",
    backToLibrary: "पुस्तकालय पर वापस जाएँ",
    submitTest: "टेस्ट जमा करें",
    previous: "पिछला",
    next: "अगला",
    bookmark: "बुकमार्क",
    bookmarked: "बुकमार्क किया गया",
    question: "प्रश्न",
    answered: "उत्तर दिए",
    easy: "आसान",
    medium: "मध्यम",
    challenging: "चुनौतीपूर्ण",
    fullTest: "पूर्ण टेस्ट",
    questions: "प्रश्न",
    marks: "अंक",
    minutes: "मिनट",
    syllabusSkill: "पाठ्यक्रम कौशल",
    answer: "उत्तर",
    explanation: "व्याख्या",
    candidateName: "अभ्यर्थी का नाम",
    rollNumber: "अनुक्रमांक",
    bookletCode: "पुस्तिका कोड",
    instructions: "निर्देश",
    responseSheet: "उत्तर पत्रक",
    testSummary: "टेस्ट सारांश",
    subject: "विषय",
    range: "प्रश्न सीमा",
    qualifying: "अर्हता मानक",
    practiceEdition: "अभ्यास संस्करण",
    candidateSignature: "अभ्यर्थी के हस्ताक्षर",
    invigilatorSignature: "निरीक्षक के हस्ताक्षर",
    date: "दिनांक",
    none: "कोई नहीं",
    negativeMarking: "ऋणात्मक अंकन",
    marksEach: "प्रति प्रश्न अंक",
    duration: "समय",
    section: "खंड",
    practiceNotice: "यह अभ्यास सामग्री दिए गए प्रश्नपत्र प्रारूप के अनुसार तैयार की गई है; यह आधिकारिक परीक्षा पुस्तिका नहीं है।",
    responseSheetHelp: "प्रत्येक प्रश्न के लिए केवल एक वृत्त भरें।",
    retainedLanguage: "व्याकरण और उत्तर की शुद्धता बनाए रखने के लिए भाषा-विषय का यह प्रश्न अंग्रेज़ी में रखा गया है।",
    demoNotice: "सुरक्षित MongoDB और ईमेल OTP सेवाएँ कॉन्फ़िगर होने तक डेमो कार्यक्षेत्र उपलब्ध है।",
    continueDemo: "डेमो कार्यक्षेत्र में जाएँ",
    welcomeBack: "पुनः स्वागत है।",
    welcomeCopy: "अपने सत्यापित विजेता खाते से प्रवेश करें या सार्वजनिक डेमो कार्यक्षेत्र खोलें।",
    secureWorkspace: "सुरक्षित संस्थान कार्यक्षेत्र",
    email: "ईमेल",
    password: "पासवर्ड",
    signInSecurely: "सुरक्षित रूप से साइन इन करें",
    forgotPassword: "पासवर्ड भूल गए?",
    createAccount: "खाता बनाएँ",
    securityNotice: "पासवर्ड और OTP कोड कभी भी पढ़ने योग्य रूप में संग्रहीत नहीं होते।",
    newFullPracticeTests: "{count} नए पूर्ण अभ्यास टेस्ट",
    levelSummary: "10 आसान · 10 मध्यम · 10 चुनौतीपूर्ण · टेस्टिंग डेटाबेस",
    closeTestStudio: "टेस्ट स्टूडियो बंद करें",
    loadingDatabase: "टेस्टिंग डेटाबेस लोड हो रहा है",
    readingQuestionModule: "पाठ्यक्रम-अनुरूप {course} प्रश्न मॉड्यूल पढ़ा जा रहा है।",
    loadingFullTest: "{course} पूर्ण टेस्ट लोड हो रहा है",
    validatingQuestions: "रनर खोलने से पहले सभी {count} प्रश्नों की जाँच हो रही है।",
    printSettings: "प्रिंट सेटिंग: सभी पृष्ठ · पोर्ट्रेट · डिफ़ॉल्ट स्केल। साफ प्रश्नपत्र के लिए ब्राउज़र हेडर और फुटर बंद करें।",
    attempted: "हल किए गए",
    notAttempted: "हल नहीं किए गए",
    current: "वर्तमान",
    readingPassage: "पठन गद्यांश",
    evsStudyNotes: "EVS अध्ययन नोट्स",
    fullTestModule: "पूर्ण टेस्ट प्रश्न मॉड्यूल",
    paperContains: "हर प्रश्नपत्र में नए तैयार किए गए प्रश्न हैं:",
    testsShown: "पूर्ण टेस्ट दिखाए गए",
    allLevels: "सभी स्तर",
    filterDifficulty: "कठिनाई के अनुसार टेस्ट छाँटें",
    printTestList: "टेस्ट सूची प्रिंट करें",
    test: "टेस्ट",
    topics: "विषय",
    closeTest: "टेस्ट बंद करें",
    preparingPaper: "पूरा प्रश्नपत्र तैयार हो रहा है…",
    workspace: "कार्यस्थल",
    examBlueprint: "परीक्षा रूपरेखा",
    signOut: "साइन आउट",
    searchWorkspace: "कार्यस्थल खोजें",
    searchAnything: "कुछ भी खोजें",
    goodMorning: "सुप्रभात, {name}।",
    attentionCopy: "विजेता संस्थान में जिन कार्यों पर ध्यान चाहिए, वे यहाँ हैं।",
    printOverview: "सारांश प्रिंट करें",
    openFullTests: "पूर्ण टेस्ट खोलें",
    activeStudents: "सक्रिय विद्यार्थी",
    batches: "बैच",
    inPreparation: "तैयारी में",
    officialTopicMap: "आधिकारिक विषय मानचित्र",
    perLevel: "प्रति स्तर 10",
    questionsEach: "प्रत्येक में {count} प्रश्न",
    questionRecords: "प्रश्न रिकॉर्ड",
    papers: "प्रश्नपत्र",
    syllabusAlignedBank: "पाठ्यक्रम-अनुरूप बैंक",
    studentPulse: "विद्यार्थी स्थिति",
    progressOverview: "प्रगति सारांश",
    manageStudents: "विद्यार्थी प्रबंधित करें",
    testingDatabase: "टेस्टिंग डेटाबेस",
    fullTestLibrary: "पूर्ण टेस्ट पुस्तकालय",
    questionsLoaded: "लोड किए गए प्रश्न",
    structureLocked: "पाठ्यक्रम संरचना सुरक्षित",
    student: "विद्यार्थी",
    batch: "बैच",
    completion: "पूर्णता",
    status: "स्थिति",
    lastActive: "अंतिम सक्रियता",
    onTrack: "सही दिशा में",
    atRisk: "जोखिम में",
    needsReview: "समीक्षा आवश्यक",
    admissionsOpen: "प्रवेश अब खुले हैं",
    admissionsCopy: "श्री विजेता यू.पी. स्कूल में सैनिक और नवोदय कोचिंग।",
    callAdmissions: "प्रवेश के लिए कॉल करें",
    visitSchool: "स्कूल वेबसाइट देखें",
    admissionsBannerAlt: "श्री विजेता सैनिक और नवोदय कोचिंग प्रवेश बैनर",
  },
  te: {
    "The paper contains 80 objective questions carrying 100 marks and must be completed in 2 hours.": "ప్రశ్నాపత్రంలో 100 మార్కులకు 80 ఆబ్జెక్టివ్ ప్రశ్నలు ఉన్నాయి; 2 గంటల్లో పూర్తి చేయాలి.",
    "Each correct response carries 1.25 marks. There is no negative marking.": "ప్రతి సరైన జవాబుకు 1.25 మార్కులు. నెగటివ్ మార్కింగ్ లేదు.",
    "Use the response sheet at the end and mark only one option for each question.": "చివర ఉన్న జవాబు పత్రాన్ని ఉపయోగించి ప్రతి ప్రశ్నకు ఒక ఎంపికను మాత్రమే గుర్తించండి.",
    "The minimum qualifying marks are 14 in Section 1, 7 in Arithmetic, and 7 in Language.": "కనీస అర్హత మార్కులు విభాగం 1లో 14, అంకగణితంలో 7, భాషలో 7.",
    "Eligible Divyang candidates receive 40 additional minutes.": "అర్హులైన దివ్యాంగ అభ్యర్థులకు 40 అదనపు నిమిషాలు లభిస్తాయి.",
    "The paper contains 125 multiple-choice questions carrying 300 marks and must be completed in 150 minutes.": "ప్రశ్నాపత్రంలో 300 మార్కులకు 125 బహుళైచ్ఛిక ప్రశ్నలు ఉన్నాయి; 150 నిమిషాల్లో పూర్తి చేయాలి.",
    "Section A Language has 25 questions, Section B Mathematics has 50, Section C Intelligence has 25, and Section D General Knowledge has 25.": "విభాగం A భాషలో 25, విభాగం B గణితంలో 50, విభాగం C మేధస్సులో 25, విభాగం D సాధారణ జ్ఞానంలో 25 ప్రశ్నలు ఉన్నాయి.",
    "Language, Intelligence, and General Knowledge questions carry 2 marks each; Mathematics questions carry 3 marks each.": "భాష, మేధస్సు, సాధారణ జ్ఞానం ప్రశ్నలకు 2 మార్కులు చొప్పున; గణితం ప్రశ్నలకు 3 మార్కులు చొప్పున ఉంటాయి.",
    "There is no negative marking. Mark only one answer for every question on the response sheet.": "నెగటివ్ మార్కింగ్ లేదు. జవాబు పత్రంలో ప్రతి ప్రశ్నకు ఒక జవాబును మాత్రమే గుర్తించండి.",
    "The official qualifying standard is 25% in each subject and 40% in aggregate, subject to the applicable category rules.": "వర్తించే వర్గ నియమాలకు లోబడి అధికారిక అర్హత ప్రమాణం ప్రతి విషయానికి 25%, మొత్తంగా 40%.",
    "The Class VI practice paper contains four 50-mark sections at Class V standard.": "క్లాస్ VI అభ్యాస పేపర్‌లో క్లాస్ V ప్రమాణానికి చెందిన నాలుగు 50 మార్కుల విభాగాలు ఉన్నాయి.",
    "The response sheet follows the OMR pattern. Mark only one answer for every question.": "జవాబు పత్రం OMR నమూనాను అనుసరిస్తుంది. ప్రతి ప్రశ్నకు ఒక జవాబును మాత్రమే గుర్తించండి.",
    "English is qualifying at 35% and is not counted in the written merit score.": "ఇంగ్లీష్‌లో 35% అర్హత అవసరం; దాని మార్కులు లిఖిత మెరిట్ స్కోరులో లెక్కించబడవు.",
    "Intelligence Test, Mathematics, and General Knowledge & Current Affairs each require 40%.": "మేధస్సు పరీక్ష, గణితం, సాధారణ జ్ఞానం మరియు సమకాలీన అంశాల్లో ప్రతి దానిలో 40% అవసరం.",
    "The official Class VI entrance paper is bilingual in English and Hindi; this generated practice edition is in English.": "అధికారిక క్లాస్ VI ప్రవేశ పేపర్ ఇంగ్లీష్, హిందీలో ద్విభాషా రూపంలో ఉంటుంది; ఈ అభ్యాస సంచిక ఎంచుకున్న ప్రదర్శన భాషలో అందుబాటులో ఉంది.",
    language: "భాష",
    chooseLanguage: "భాషను ఎంచుకోండి",
    dashboard: "డ్యాష్‌బోర్డ్",
    aiHoloTutor: "AI హోలో ట్యూటర్",
    principalControl: "ప్రిన్సిపల్ నియంత్రణ",
    students: "విద్యార్థులు",
    classes: "తరగతులు",
    mockTests: "మాక్ టెస్టులు",
    batchExams: "బ్యాచ్ పరీక్షలు",
    resources: "నోట్స్ మరియు టెస్టులు",
    progress: "పురోగతి",
    parents: "తల్లిదండ్రులు",
    syllabus: "సిలబస్",
    settings: "సెట్టింగ్స్",
    instituteLogin: "సంస్థ లాగిన్",
    openDemo: "డెమో వర్క్‌స్పేస్ తెరవండి",
    backToWebsite: "వెబ్‌సైట్‌కు తిరిగి వెళ్లండి",
    signIn: "వర్క్‌స్పేస్‌లో సైన్ ఇన్ చేయండి",
    courseLibrary: "కోర్సు లైబ్రరీ",
    chooseExam: "ప్రవేశ పరీక్షను ఎంచుకోండి",
    printComplete: "పూర్తి ప్రశ్నాపత్రాన్ని ముద్రించండి",
    savePdf: "పూర్తి ప్రశ్నాపత్రాన్ని PDFగా సేవ్ చేయండి",
    set: "సెట్",
    secureExamSets: "సురక్షిత పరీక్షా సెట్లు",
    chooseExamSet: "ప్రశ్నాపత్రం సెట్‌ను ఎంచుకోండి",
    uniqueOrder: "ప్రత్యేక క్రమం",
    sameValidatedPaper: "అదే ధృవీకరించిన ప్రశ్నాపత్రం",
    examSetAssurance: "అన్ని ప్రశ్నలు, మార్కులు, విభాగాలు మరియు సిలబస్ కవరేజ్ ఒకేలా ఉంటాయి. ప్రశ్నలు మరియు ఎంపికల క్రమం మాత్రమే మారుతుంది.",
    questionsShuffled: "ప్రశ్నల క్రమం మార్చబడింది",
    optionsShuffled: "ఎంపికల క్రమం మార్చబడింది",
    answersRemapped: "జవాబు కీ తిరిగి అమర్చబడింది",
    printSetHelp: "ఈ టెస్ట్‌కు ముద్రించాల్సిన బుక్‌లెట్ కోడ్‌ను ఎంచుకోండి.",
    saveSetHelp: "బుక్‌లెట్ కోడ్‌ను ఎంచుకుని, బ్రౌజర్ ప్రింట్ విండోలో PDFగా సేవ్ చేయండి ఎంచుకోండి.",
    printSet: "సెట్ {set} ముద్రించండి",
    saveSetPdf: "సెట్ {set}ను PDFగా సేవ్ చేయండి",
    closeExamSetDialog: "ప్రశ్నాపత్రం సెట్ ఎంపికను మూసివేయండి",
    cancel: "రద్దు చేయండి",
    backToLibrary: "లైబ్రరీకి తిరిగి వెళ్లండి",
    submitTest: "టెస్ట్ సమర్పించండి",
    previous: "మునుపటి",
    next: "తదుపరి",
    bookmark: "బుక్‌మార్క్",
    bookmarked: "బుక్‌మార్క్ అయింది",
    question: "ప్రశ్న",
    answered: "జవాబిచ్చినవి",
    easy: "సులభం",
    medium: "మధ్యస్థం",
    challenging: "సవాలుతో కూడినది",
    fullTest: "పూర్తి టెస్ట్",
    questions: "ప్రశ్నలు",
    marks: "మార్కులు",
    minutes: "నిమిషాలు",
    syllabusSkill: "సిలబస్ నైపుణ్యం",
    answer: "జవాబు",
    explanation: "వివరణ",
    candidateName: "అభ్యర్థి పేరు",
    rollNumber: "రోల్ నంబర్",
    bookletCode: "బుక్‌లెట్ కోడ్",
    instructions: "సూచనలు",
    responseSheet: "జవాబు పత్రం",
    testSummary: "టెస్ట్ సారాంశం",
    subject: "విషయం",
    range: "ప్రశ్నల పరిధి",
    qualifying: "అర్హత ప్రమాణం",
    practiceEdition: "అభ్యాస సంచిక",
    candidateSignature: "అభ్యర్థి సంతకం",
    invigilatorSignature: "ఇన్విజిలేటర్ సంతకం",
    date: "తేదీ",
    none: "లేదు",
    negativeMarking: "నెగటివ్ మార్కింగ్",
    marksEach: "ప్రతి ప్రశ్నకు మార్కులు",
    duration: "వ్యవధి",
    section: "విభాగం",
    practiceNotice: "ఇది పేర్కొన్న ప్రశ్నాపత్ర నమూనా ప్రకారం రూపొందించిన అభ్యాస సామగ్రి; అధికారిక పరీక్ష పుస్తకం కాదు.",
    responseSheetHelp: "ప్రతి ప్రశ్నకు ఒక వృత్తాన్ని మాత్రమే నింపండి.",
    retainedLanguage: "వ్యాకరణం మరియు జవాబు సరైనదిగా ఉండేందుకు ఈ భాషా-విషయ ప్రశ్నను ఇంగ్లీషులోనే ఉంచాము.",
    demoNotice: "సురక్షిత MongoDB మరియు ఇమెయిల్ OTP సేవలు కాన్ఫిగర్ అయ్యే వరకు డెమో వర్క్‌స్పేస్ అందుబాటులో ఉంటుంది.",
    continueDemo: "డెమో వర్క్‌స్పేస్‌లోకి వెళ్లండి",
    welcomeBack: "మళ్లీ స్వాగతం.",
    welcomeCopy: "ధృవీకరించిన విజేత ఖాతాతో ప్రవేశించండి లేదా పబ్లిక్ డెమో వర్క్‌స్పేస్‌ను తెరవండి.",
    secureWorkspace: "సురక్షిత సంస్థ వర్క్‌స్పేస్",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    signInSecurely: "సురక్షితంగా సైన్ ఇన్ చేయండి",
    forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    createAccount: "ఖాతాను సృష్టించండి",
    securityNotice: "పాస్‌వర్డ్‌లు మరియు OTP కోడ్‌లు చదవగలిగే రూపంలో ఎప్పుడూ నిల్వ చేయబడవు.",
    newFullPracticeTests: "{count} కొత్త పూర్తి అభ్యాస టెస్టులు",
    levelSummary: "10 సులభం · 10 మధ్యస్థం · 10 సవాలు · టెస్టింగ్ డేటాబేస్",
    closeTestStudio: "టెస్ట్ స్టూడియోను మూసివేయండి",
    loadingDatabase: "టెస్టింగ్ డేటాబేస్ లోడ్ అవుతోంది",
    readingQuestionModule: "సిలబస్‌కు అనుగుణమైన {course} ప్రశ్న మాడ్యూల్ చదువుతోంది.",
    loadingFullTest: "{course} పూర్తి టెస్ట్ లోడ్ అవుతోంది",
    validatingQuestions: "రన్నర్ తెరవడానికి ముందు మొత్తం {count} ప్రశ్నలను తనిఖీ చేస్తోంది.",
    printSettings: "ప్రింట్ సెట్టింగులు: అన్ని పేజీలు · పోర్ట్రెయిట్ · డిఫాల్ట్ స్కేల్. శుభ్రమైన పేపర్ కోసం బ్రౌజర్ హెడర్‌లు, ఫుటర్‌లను ఆఫ్ చేయండి.",
    attempted: "ప్రయత్నించినవి",
    notAttempted: "ప్రయత్నించనివి",
    current: "ప్రస్తుత",
    readingPassage: "పఠన గద్యభాగం",
    evsStudyNotes: "EVS అధ్యయన నోట్స్",
    fullTestModule: "పూర్తి టెస్ట్ ప్రశ్న మాడ్యూల్",
    paperContains: "ప్రతి పేపర్‌లో కొత్తగా రూపొందించిన ప్రశ్నలు ఉన్నాయి:",
    testsShown: "పూర్తి టెస్టులు చూపబడ్డాయి",
    allLevels: "అన్ని స్థాయులు",
    filterDifficulty: "కఠినత ఆధారంగా టెస్టులను వడపోయండి",
    printTestList: "టెస్ట్ జాబితాను ముద్రించండి",
    test: "టెస్ట్",
    topics: "అంశాలు",
    closeTest: "టెస్ట్‌ను మూసివేయండి",
    preparingPaper: "పూర్తి ప్రశ్నాపత్రం సిద్ధమవుతోంది…",
    workspace: "వర్క్‌స్పేస్",
    examBlueprint: "పరీక్ష రూపరేఖ",
    signOut: "సైన్ అవుట్",
    searchWorkspace: "వర్క్‌స్పేస్‌లో వెతకండి",
    searchAnything: "ఏదైనా వెతకండి",
    goodMorning: "శుభోదయం, {name}.",
    attentionCopy: "విజేత సంస్థలో శ్రద్ధ అవసరమైన అంశాలు ఇక్కడ ఉన్నాయి.",
    printOverview: "సారాంశాన్ని ముద్రించండి",
    openFullTests: "పూర్తి టెస్టులు తెరవండి",
    activeStudents: "క్రియాశీల విద్యార్థులు",
    batches: "బ్యాచ్‌లు",
    inPreparation: "సిద్ధమవుతున్నారు",
    officialTopicMap: "అధికారిక అంశ మ్యాప్",
    perLevel: "ప్రతి స్థాయికి 10",
    questionsEach: "ఒక్కో దాంట్లో {count} ప్రశ్నలు",
    questionRecords: "ప్రశ్న రికార్డులు",
    papers: "పేపర్లు",
    syllabusAlignedBank: "సిలబస్‌కు అనుగుణమైన బ్యాంక్",
    studentPulse: "విద్యార్థుల స్థితి",
    progressOverview: "పురోగతి సారాంశం",
    manageStudents: "విద్యార్థులను నిర్వహించండి",
    testingDatabase: "టెస్టింగ్ డేటాబేస్",
    fullTestLibrary: "పూర్తి టెస్ట్ లైబ్రరీ",
    questionsLoaded: "లోడ్ చేసిన ప్రశ్నలు",
    structureLocked: "సిలబస్ నిర్మాణం భద్రం",
    student: "విద్యార్థి",
    batch: "బ్యాచ్",
    completion: "పూర్తి శాతం",
    status: "స్థితి",
    lastActive: "చివరిసారి క్రియాశీలం",
    onTrack: "సరైన దిశలో",
    atRisk: "ప్రమాదంలో",
    needsReview: "సమీక్ష అవసరం",
    admissionsOpen: "ప్రవేశాలు ఇప్పుడు ప్రారంభమయ్యాయి",
    admissionsCopy: "శ్రీ విజేత యు.పి స్కూల్‌లో సైనిక్ మరియు నవోదయ కోచింగ్.",
    callAdmissions: "ప్రవేశాల కోసం కాల్ చేయండి",
    visitSchool: "స్కూల్ వెబ్‌సైట్‌ను చూడండి",
    admissionsBannerAlt: "శ్రీ విజేత సైనిక్ మరియు నవోదయ కోచింగ్ ప్రవేశాల బ్యానర్",
  },
};

export function translateUi(key, locale = DEFAULT_LOCALE, replacements = {}) {
  const template = UI_MESSAGES[locale]?.[key] || UI_MESSAGES.en[key] || key;
  return Object.entries(replacements).reduce(
    (value, [name, replacement]) => value.replaceAll(`{${name}}`, String(replacement)),
    template,
  );
}

const SUBJECTS = {
  hi: {
    "Mental Ability": "मानसिक योग्यता",
    "Environmental Studies": "पर्यावरण अध्ययन",
    Arithmetic: "अंकगणित",
    Language: "भाषा",
    English: "अंग्रेज़ी",
    Mathematics: "गणित",
    Intelligence: "बुद्धिमत्ता",
    "Intelligence Test": "बुद्धिमत्ता परीक्षण",
    "General Knowledge": "सामान्य ज्ञान",
    "General Knowledge & Current Affairs": "सामान्य ज्ञान एवं समसामयिकी",
  },
  te: {
    "Mental Ability": "మానసిక సామర్థ్యం",
    "Environmental Studies": "పర్యావరణ అధ్యయనాలు",
    Arithmetic: "అంకగణితం",
    Language: "భాష",
    English: "ఇంగ్లీష్",
    Mathematics: "గణితం",
    Intelligence: "మేధస్సు",
    "Intelligence Test": "మేధస్సు పరీక్ష",
    "General Knowledge": "సాధారణ జ్ఞానం",
    "General Knowledge & Current Affairs": "సాధారణ జ్ఞానం మరియు సమకాలీన అంశాలు",
  },
};

const EXACT_TEXT = {
  hi: {
    "Select the number that completes the pattern.": "पैटर्न पूरा करने वाली संख्या चुनिए।",
    "Select the letter that completes the alphabetical pattern.": "वर्णमाला पैटर्न पूरा करने वाला अक्षर चुनिए।",
    "Choose the figure that completes the increasing visual pattern.": "बढ़ते हुए दृश्य पैटर्न को पूरा करने वाली आकृति चुनिए।",
    "The table and matching bar diagram show project counts. Which category has the tallest bar?": "तालिका और बार-आरेख परियोजना की संख्याएँ दिखाते हैं। सबसे ऊँचा बार किस श्रेणी का है?",
    "North-east": "उत्तर-पूर्व", "North-west": "उत्तर-पश्चिम", "South-east": "दक्षिण-पूर्व", "South-west": "दक्षिण-पश्चिम",
    North: "उत्तर", South: "दक्षिण", East: "पूर्व", West: "पश्चिम",
    Daughter: "बेटी", Mother: "माता", Aunt: "चाची/मौसी", Grandmother: "दादी/नानी",
    "Acute angle": "न्यून कोण", "Right angle": "समकोण", "Obtuse angle": "अधिक कोण", "Straight angle": "सरल कोण", "Reflex angle": "प्रतिवर्ती कोण",
    triangle: "त्रिभुज", square: "वर्ग", circle: "वृत्त", pentagon: "पंचभुज", hexagon: "षट्भुज",
    "Bengal tiger": "बंगाल टाइगर", "Asian elephant": "एशियाई हाथी", "Indian Navy": "भारतीय नौसेना", "Indian Army": "भारतीय थल सेना", "Indian Air Force": "भारतीय वायु सेना",
    "New Delhi": "नई दिल्ली", Rajasthan: "राजस्थान", Jaipur: "जयपुर", Diwali: "दीवाली", Monsoon: "मानसून",
    Roots: "जड़ें", Flowers: "फूल", Fruits: "फल", Seeds: "बीज", Frog: "मेंढक", Camel: "ऊँट", Eagle: "गरुड़", Cow: "गाय",
    Heart: "हृदय", Lungs: "फेफड़े", Mouth: "मुँह", Nose: "नाक", Tongue: "जीभ", Skin: "त्वचा", Ear: "कान",
    Condensation: "संघनन", Evaporation: "वाष्पीकरण", Protein: "प्रोटीन", Cotton: "कपास", Rice: "चावल", Plain: "मैदान", Mountain: "पर्वत", Valley: "घाटी", Island: "द्वीप",
    "solar energy": "सौर ऊर्जा", coal: "कोयला", petrol: "पेट्रोल", diesel: "डीज़ल", thermometer: "थर्मामीटर", seismograph: "भूकंपलेखी", "terrace farming": "सीढ़ीदार खेती",
    "planting trees": "पेड़ लगाना", "official government website": "आधिकारिक सरकारी वेबसाइट", drying: "सुखाना", evaporation: "वाष्पीकरण", heart: "हृदय",
  },
  te: {
    "Select the number that completes the pattern.": "నమూనాను పూర్తి చేసే సంఖ్యను ఎంచుకోండి.",
    "Select the letter that completes the alphabetical pattern.": "అక్షర క్రమ నమూనాను పూర్తి చేసే అక్షరాన్ని ఎంచుకోండి.",
    "Choose the figure that completes the increasing visual pattern.": "పెరుగుతున్న దృశ్య నమూనాను పూర్తి చేసే ఆకారాన్ని ఎంచుకోండి.",
    "The table and matching bar diagram show project counts. Which category has the tallest bar?": "పట్టిక మరియు బార్ చిత్రంలో ప్రాజెక్టుల సంఖ్యలు ఉన్నాయి. అత్యంత ఎత్తైన బార్ ఏ వర్గానికి చెందింది?",
    "North-east": "ఈశాన్యం", "North-west": "వాయువ్యం", "South-east": "ఆగ్నేయం", "South-west": "నైరుతి",
    North: "ఉత్తరం", South: "దక్షిణం", East: "తూర్పు", West: "పడమర",
    Daughter: "కుమార్తె", Mother: "తల్లి", Aunt: "పిన్ని/అత్త", Grandmother: "అమ్మమ్మ/నానమ్మ",
    "Acute angle": "లఘు కోణం", "Right angle": "లంబ కోణం", "Obtuse angle": "అధిక కోణం", "Straight angle": "సరళ కోణం", "Reflex angle": "ప్రతిబింబ కోణం",
    triangle: "త్రిభుజం", square: "చతురస్రం", circle: "వృత్తం", pentagon: "పంచభుజం", hexagon: "షట్భుజం",
    "Bengal tiger": "బెంగాల్ పులి", "Asian elephant": "ఆసియా ఏనుగు", "Indian Navy": "భారత నౌకాదళం", "Indian Army": "భారత సైన్యం", "Indian Air Force": "భారత వైమానిక దళం",
    "New Delhi": "న్యూఢిల్లీ", Rajasthan: "రాజస్థాన్", Jaipur: "జైపూర్", Diwali: "దీపావళి", Monsoon: "రుతుపవనాలు",
    Roots: "వేర్లు", Flowers: "పువ్వులు", Fruits: "పండ్లు", Seeds: "విత్తనాలు", Frog: "కప్ప", Camel: "ఒంటె", Eagle: "గద్ద", Cow: "ఆవు",
    Heart: "గుండె", Lungs: "ఊపిరితిత్తులు", Mouth: "నోరు", Nose: "ముక్కు", Tongue: "నాలుక", Skin: "చర్మం", Ear: "చెవి",
    Condensation: "సాంద్రీకరణ", Evaporation: "ఆవిరీకరణ", Protein: "ప్రోటీన్", Cotton: "పత్తి", Rice: "వరి", Plain: "మైదానం", Mountain: "పర్వతం", Valley: "లోయ", Island: "ద్వీపం",
    "solar energy": "సౌర శక్తి", coal: "బొగ్గు", petrol: "పెట్రోలు", diesel: "డీజిల్", thermometer: "థర్మామీటర్", seismograph: "భూకంపలేఖిని", "terrace farming": "మెట్ల సాగు",
    "planting trees": "చెట్లు నాటడం", "official government website": "అధికారిక ప్రభుత్వ వెబ్‌సైట్", drying: "ఎండబెట్టడం", evaporation: "ఆవిరీకరణ", heart: "గుండె",
  },
};

const STEM_RULES = {
  hi: [
    [/^Find the next number: (.+)$/i, (_, values) => `अगली संख्या ज्ञात कीजिए: ${values}`],
    [/^Complete the letter pattern: (.+)$/i, (_, values) => `अक्षर पैटर्न पूरा कीजिए: ${values}`],
    [/^What is the place value of the digit (.+) in (.+)\?$/i, (_, digit, number) => `${number} में अंक ${digit} का स्थानीय मान क्या है?`],
    [/^What is the HCF of (.+) and (.+)\?$/i, (_, first, second) => `${first} और ${second} का महत्तम समापवर्तक क्या है?`],
    [/^Which option is a prime number between (.+) and (.+)\?$/i, (_, first, second) => `${first} और ${second} के बीच अभाज्य संख्या वाला विकल्प चुनिए।`],
    [/^Add the like fractions (.+)\.$/i, (_, expression) => `समान हर वाली भिन्नों को जोड़िए: ${expression}।`],
    [/^Arrange (.+) in ascending order\.$/i, (_, values) => `${values} को आरोही क्रम में लगाइए।`],
    [/^Find the average of (.+)\.$/i, (_, values) => `${values} का औसत ज्ञात कीजिए।`],
    [/^What is (.+)% of (.+)\?$/i, (_, rate, whole) => `${whole} का ${rate}% कितना है?`],
    [/^Write (.+) as a decimal\.$/i, (_, value) => `${value} को दशमलव में लिखिए।`],
    [/^Find the volume of a cuboid (.+)\.$/i, (_, dimensions) => `${dimensions} वाले घनाभ का आयतन ज्ञात कीजिए।`],
    [/^A circle has a radius of (.+)\. What is its diameter\?$/i, (_, radius) => `एक वृत्त की त्रिज्या ${radius} है। उसका व्यास कितना है?`],
    [/^A regular plane figure has (.+) equal sides, each (.+) long\. What is its perimeter\?$/i, (_, sides, length) => `एक नियमित समतल आकृति की ${sides} बराबर भुजाएँ हैं और प्रत्येक ${length} लंबी है। उसका परिमाप क्या है?`],
    [/^How should an angle measuring (.+) be classified\?$/i, (_, angle) => `${angle} माप वाले कोण का प्रकार बताइए।`],
    [/^What is the (complement|supplement) of an angle measuring (.+)\?$/i, (_, relation, angle) => `${angle} माप वाले कोण का ${relation === "complement" ? "पूरक" : "संपूरक"} कोण कितना है?`],
    [/^Two angles form a straight line\. If one angle measures (.+), what is the other angle\?$/i, (_, angle) => `दो कोण एक सरल रेखा बनाते हैं। एक कोण ${angle} है, तो दूसरा कोण कितना है?`],
    [/^Three adjacent angles form a straight line\. Two measure (.+) and (.+)\. What is the third angle\?$/i, (_, first, second) => `तीन आसन्न कोण एक सरल रेखा बनाते हैं। दो कोण ${first} और ${second} हैं। तीसरा कोण कितना है?`],
    [/^A rectangular training ground is (.+) long and (.+) wide\. What is its perimeter\?$/i, (_, length, width) => `एक आयताकार मैदान ${length} लंबा और ${width} चौड़ा है। उसका परिमाप क्या है?`],
    [/^Convert (.+) completely into millilitres\.$/i, (_, value) => `${value} को पूरी तरह मिलीलीटर में बदलिए।`],
    [/^Which Roman numeral represents (.+)\?$/i, (_, value) => `${value} को दर्शाने वाला रोमन अंक चुनिए।`],
    [/^A cyclist travels at (.+) per hour for (.+) hours\. What distance is covered\?$/i, (_, speed, hours) => `एक साइकिल चालक ${speed} प्रति घंटे की गति से ${hours} घंटे चलता है। उसने कितनी दूरी तय की?`],
    [/^The morning temperature was (.+) and rose by (.+)\. What was the later temperature\?$/i, (_, start, rise) => `सुबह का तापमान ${start} था और ${rise} बढ़ा। बाद का तापमान कितना था?`],
    [/^(.+) starts with (.+) counters, receives (.+), and gives away (.+)\. How many counters remain\?$/i, (_, name, first, second, third) => `${name} के पास ${first} काउंटर थे, ${second} और मिले तथा ${third} दे दिए। कितने काउंटर बचे?`],
    [/^(.+) is related to (.+) in the same way that (.+) is related to __\.$/i, (_, first, second, third) => `${first} का ${second} से वही संबंध है जो ${third} का __ से है।`],
    [/^In a classification set beginning with (.+), which number does not belong with the other multiples of (.+)\?$/i, (_, base, factor) => `${base} से शुरू समूह में कौन-सी संख्या ${factor} के अन्य गुणजों से अलग है?`],
    [/^A cadet walks (.+) east and then (.+) north\. In which direction is the cadet from the starting point\?$/i, (_, east, north) => `एक कैडेट ${east} पूर्व और फिर ${north} उत्तर चलता है। आरंभिक बिंदु से वह किस दिशा में है?`],
    [/^At (.+) (\d+), which option correctly identifies the (.+)\?$/i, (_, context, station, description) => `${translateAcademicText(description, "hi")} की सही पहचान करने वाला विकल्प चुनिए।`],
  ],
  te: [
    [/^Find the next number: (.+)$/i, (_, values) => `తదుపరి సంఖ్యను కనుగొనండి: ${values}`],
    [/^Complete the letter pattern: (.+)$/i, (_, values) => `అక్షర నమూనాను పూర్తి చేయండి: ${values}`],
    [/^What is the place value of the digit (.+) in (.+)\?$/i, (_, digit, number) => `${number}లో ${digit} అంకె స్థాన విలువ ఎంత?`],
    [/^What is the HCF of (.+) and (.+)\?$/i, (_, first, second) => `${first}, ${second}ల గరిష్ఠ సామాన్య భాజకం ఎంత?`],
    [/^Which option is a prime number between (.+) and (.+)\?$/i, (_, first, second) => `${first}, ${second} మధ్య ఉన్న ప్రధాన సంఖ్యను ఎంచుకోండి.`],
    [/^Add the like fractions (.+)\.$/i, (_, expression) => `సమాన హారాల భిన్నాలను కలపండి: ${expression}.`],
    [/^Arrange (.+) in ascending order\.$/i, (_, values) => `${values}ను ఆరోహణ క్రమంలో అమర్చండి.`],
    [/^Find the average of (.+)\.$/i, (_, values) => `${values} సగటును కనుగొనండి.`],
    [/^What is (.+)% of (.+)\?$/i, (_, rate, whole) => `${whole}లో ${rate}% ఎంత?`],
    [/^Write (.+) as a decimal\.$/i, (_, value) => `${value}ను దశాంశంగా రాయండి.`],
    [/^Find the volume of a cuboid (.+)\.$/i, (_, dimensions) => `${dimensions} కొలతలున్న ఘనాయతం ఘనపరిమాణాన్ని కనుగొనండి.`],
    [/^A circle has a radius of (.+)\. What is its diameter\?$/i, (_, radius) => `ఒక వృత్తం వ్యాసార్థం ${radius}. దాని వ్యాసం ఎంత?`],
    [/^A regular plane figure has (.+) equal sides, each (.+) long\. What is its perimeter\?$/i, (_, sides, length) => `ఒక క్రమ సమతల ఆకారానికి ${sides} సమాన భుజాలు ఉన్నాయి; ప్రతి భుజం ${length}. దాని పరిధి ఎంత?`],
    [/^How should an angle measuring (.+) be classified\?$/i, (_, angle) => `${angle} కొలత గల కోణం ఏ రకం?`],
    [/^What is the (complement|supplement) of an angle measuring (.+)\?$/i, (_, relation, angle) => `${angle} కోణానికి ${relation === "complement" ? "పూరక" : "సంపూరక"} కోణం ఎంత?`],
    [/^Two angles form a straight line\. If one angle measures (.+), what is the other angle\?$/i, (_, angle) => `రెండు కోణాలు సరళ రేఖను ఏర్పరుస్తాయి. ఒక కోణం ${angle} అయితే మరొకటి ఎంత?`],
    [/^Three adjacent angles form a straight line\. Two measure (.+) and (.+)\. What is the third angle\?$/i, (_, first, second) => `మూడు ఆనుకుని ఉన్న కోణాలు సరళ రేఖను ఏర్పరుస్తాయి. రెండు ${first}, ${second}. మూడవ కోణం ఎంత?`],
    [/^A rectangular training ground is (.+) long and (.+) wide\. What is its perimeter\?$/i, (_, length, width) => `ఒక దీర్ఘచతురస్ర మైదానం ${length} పొడవు, ${width} వెడల్పు. దాని పరిధి ఎంత?`],
    [/^Convert (.+) completely into millilitres\.$/i, (_, value) => `${value}ను పూర్తిగా మిల్లీలీటర్లలోకి మార్చండి.`],
    [/^Which Roman numeral represents (.+)\?$/i, (_, value) => `${value}ను సూచించే రోమన్ సంఖ్యను ఎంచుకోండి.`],
    [/^A cyclist travels at (.+) per hour for (.+) hours\. What distance is covered\?$/i, (_, speed, hours) => `ఒక సైకిల్ ప్రయాణికుడు గంటకు ${speed} వేగంతో ${hours} గంటలు ప్రయాణించాడు. దూరం ఎంత?`],
    [/^The morning temperature was (.+) and rose by (.+)\. What was the later temperature\?$/i, (_, start, rise) => `ఉదయం ఉష్ణోగ్రత ${start}; అది ${rise} పెరిగింది. తరువాతి ఉష్ణోగ్రత ఎంత?`],
    [/^(.+) starts with (.+) counters, receives (.+), and gives away (.+)\. How many counters remain\?$/i, (_, name, first, second, third) => `${name} వద్ద ${first} కౌంటర్లు ఉన్నాయి; ${second} వచ్చాయి, ${third} ఇచ్చారు. ఎన్ని మిగిలాయి?`],
    [/^(.+) is related to (.+) in the same way that (.+) is related to __\.$/i, (_, first, second, third) => `${first}కు ${second}తో ఉన్న సంబంధమే ${third}కు __తో ఉంది.`],
    [/^In a classification set beginning with (.+), which number does not belong with the other multiples of (.+)\?$/i, (_, base, factor) => `${base}తో ప్రారంభమయ్యే వర్గీకరణలో ${factor} ఇతర గుణితాలకు చెందని సంఖ్య ఏది?`],
    [/^A cadet walks (.+) east and then (.+) north\. In which direction is the cadet from the starting point\?$/i, (_, east, north) => `ఒక కేడెట్ ${east} తూర్పుకు, తరువాత ${north} ఉత్తరానికి నడిచాడు. ప్రారంభ స్థానం నుంచి అతను ఏ దిశలో ఉన్నాడు?`],
    [/^At (.+) (\d+), which option correctly identifies the (.+)\?$/i, (_, context, station, description) => `${translateAcademicText(description, "te")}ను సరిగ్గా గుర్తించే ఎంపికను ఎంచుకోండి.`],
  ],
};

const PHRASES = {
  hi: [
    ["Simplify", "सरल कीजिए"], ["Convert", "बदलिए"], ["During", "के दौरान"], ["is completing", "पूरा कर रहे हैं"], ["buys", "खरीदते हैं"], ["Why", "क्यों"],
    ["Which answer", "कौन-सा उत्तर"], ["the group discusses", "समूह चर्चा करता है"], ["practice sheet", "अभ्यास पत्र"], ["project notebook", "परियोजना पुस्तिका"],
    ["How is", "किस प्रकार"], ["is the sister of", "की बहन है"], ["is the son of", "का पुत्र है"], ["related to", "से संबंधित है"], ["siblings", "भाई-बहन"], ["daughter", "बेटी"], ["son", "पुत्र"],
    ["Which option correctly identifies the", "कौन-सा विकल्प सही पहचान करता है"], ["Which option", "कौन-सा विकल्प"], ["Which figure", "कौन-सी आकृति"], ["Which number", "कौन-सी संख्या"],
    ["What is", "क्या है"], ["How many", "कितने"], ["Choose", "चुनिए"], ["Select", "चुनिए"], ["Find", "ज्ञात कीजिए"], ["Complete", "पूरा कीजिए"],
    ["correctly", "सही रूप से"], ["correct", "सही"], ["ascending order", "आरोही क्रम"], ["descending order", "अवरोही क्रम"], ["equal sides", "बराबर भुजाएँ"],
    ["perimeter", "परिमाप"], ["volume", "आयतन"], ["diameter", "व्यास"], ["radius", "त्रिज्या"], ["angle", "कोण"], ["number", "संख्या"], ["figure", "आकृति"],
    ["national animal", "राष्ट्रीय पशु"], ["capital of India", "भारत की राजधानी"], ["renewable source", "नवीकरणीय स्रोत"], ["organ that pumps blood", "रक्त पंप करने वाला अंग"],
    ["instrument used to measure temperature", "तापमान मापने का यंत्र"], ["process that changes liquid water into vapour", "द्रव जल को वाष्प में बदलने की प्रक्रिया"],
    ["branch that protects India at sea", "समुद्र में भारत की रक्षा करने वाली शाखा"], ["number of players in a cricket team on the field", "मैदान पर क्रिकेट टीम के खिलाड़ियों की संख्या"],
    ["most reliable source for a current official government announcement", "वर्तमान आधिकारिक सरकारी घोषणा का सबसे विश्वसनीय स्रोत"],
    ["method that preserves food by removing moisture", "नमी हटाकर भोजन सुरक्षित रखने की विधि"], ["farming method commonly used on steep hill slopes", "खड़ी पहाड़ी ढलानों पर प्रयुक्त खेती की विधि"],
    ["international organisation focused on global health", "वैश्विक स्वास्थ्य पर केंद्रित अंतरराष्ट्रीय संगठन"], ["Indian award associated with literature", "साहित्य से जुड़ा भारतीय पुरस्कार"],
    ["the same rate", "उसी दर"], ["selling price", "विक्रय मूल्य"], ["simple interest", "साधारण ब्याज"], ["prime number", "अभाज्य संख्या"], ["place value", "स्थानीय मान"],
  ],
  te: [
    ["Simplify", "సరళీకరించండి"], ["Convert", "మార్చండి"], ["During", "సమయంలో"], ["is completing", "పూర్తి చేస్తున్నారు"], ["buys", "కొంటారు"], ["Why", "ఎందుకు"],
    ["Which answer", "ఏ జవాబు"], ["the group discusses", "బృందం చర్చిస్తుంది"], ["practice sheet", "అభ్యాస పత్రం"], ["project notebook", "ప్రాజెక్ట్ నోట్‌బుక్"],
    ["How is", "ఎలా"], ["is the sister of", "కు సోదరి"], ["is the son of", "కు కుమారుడు"], ["related to", "తో సంబంధం ఉంది"], ["siblings", "తోబుట్టువులు"], ["daughter", "కుమార్తె"], ["son", "కుమారుడు"],
    ["Which option correctly identifies the", "ఏ ఎంపిక సరిగ్గా గుర్తిస్తుంది"], ["Which option", "ఏ ఎంపిక"], ["Which figure", "ఏ ఆకారం"], ["Which number", "ఏ సంఖ్య"],
    ["What is", "ఏమిటి"], ["How many", "ఎన్ని"], ["Choose", "ఎంచుకోండి"], ["Select", "ఎంచుకోండి"], ["Find", "కనుగొనండి"], ["Complete", "పూర్తి చేయండి"],
    ["correctly", "సరిగ్గా"], ["correct", "సరైన"], ["ascending order", "ఆరోహణ క్రమం"], ["descending order", "అవరోహణ క్రమం"], ["equal sides", "సమాన భుజాలు"],
    ["perimeter", "పరిధి"], ["volume", "ఘనపరిమాణం"], ["diameter", "వ్యాసం"], ["radius", "వ్యాసార్థం"], ["angle", "కోణం"], ["number", "సంఖ్య"], ["figure", "ఆకారం"],
    ["national animal", "జాతీయ జంతువు"], ["capital of India", "భారతదేశ రాజధాని"], ["renewable source", "పునరుత్పాదక వనరు"], ["organ that pumps blood", "రక్తాన్ని పంపే అవయవం"],
    ["instrument used to measure temperature", "ఉష్ణోగ్రత కొలిచే పరికరం"], ["process that changes liquid water into vapour", "ద్రవ నీటిని ఆవిరిగా మార్చే ప్రక్రియ"],
    ["branch that protects India at sea", "సముద్రంలో భారతదేశాన్ని రక్షించే దళం"], ["number of players in a cricket team on the field", "మైదానంలో క్రికెట్ జట్టులోని ఆటగాళ్ల సంఖ్య"],
    ["most reliable source for a current official government announcement", "ప్రస్తుత అధికారిక ప్రభుత్వ ప్రకటనకు అత్యంత విశ్వసనీయ వనరు"],
    ["method that preserves food by removing moisture", "తేమ తొలగించి ఆహారాన్ని నిల్వ చేసే పద్ధతి"], ["farming method commonly used on steep hill slopes", "ఏటవాలు కొండలపై సాధారణంగా ఉపయోగించే సాగు పద్ధతి"],
    ["international organisation focused on global health", "ప్రపంచ ఆరోగ్యంపై దృష్టి పెట్టే అంతర్జాతీయ సంస్థ"], ["Indian award associated with literature", "సాహిత్యానికి సంబంధించిన భారతీయ పురస్కారం"],
    ["the same rate", "అదే రేటు"], ["selling price", "అమ్మకపు ధర"], ["simple interest", "సాధారణ వడ్డీ"], ["prime number", "ప్రధాన సంఖ్య"], ["place value", "స్థాన విలువ"],
  ],
};

export function translateSubject(value, locale = DEFAULT_LOCALE) {
  if (locale !== "en" && String(value).includes(" + ")) {
    return String(value).split(" + ").map((item) => SUBJECTS[locale]?.[item] || item).join(" + ");
  }
  return SUBJECTS[locale]?.[value] || value;
}

export function translateAcademicText(value, locale = DEFAULT_LOCALE) {
  if (locale === "en" || value == null) return value == null ? "" : String(value);
  const original = String(value);
  const exact = EXACT_TEXT[locale]?.[original];
  if (exact) return exact;
  for (const [pattern, render] of STEM_RULES[locale] || []) {
    const match = original.match(pattern);
    if (match) return render(...match);
  }
  let translated = original;
  for (const [source, target] of PHRASES[locale] || []) translated = translated.replaceAll(source, target);
  return EXACT_TEXT[locale]?.[translated] || translated;
}

export function isRetainedLanguageSubject(question) {
  return ["Language", "English"].includes(question?.subject);
}

export function localizeQuestion(question, locale = DEFAULT_LOCALE) {
  if (!question || locale === "en") return question;
  const retained = isRetainedLanguageSubject(question);
  const localize = retained ? (value) => value : (value) => translateAcademicText(value, locale);
  return {
    ...question,
    text: localize(question.text || question.stem),
    stem: localize(question.stem || question.text),
    passage: localize(question.passage),
    explanation: localize(question.explanation),
    subjectLabel: translateSubject(question.subject, locale),
    topicLabel: translateAcademicText(question.topic, locale),
    options: (question.options || []).map((option) => ({
      ...option,
      label: localize(option.label ?? option.text),
      text: localize(option.text ?? option.label),
    })),
    localization: { locale, retainedLanguageSubject: retained },
  };
}

export function localizeTest(test, locale = DEFAULT_LOCALE) {
  if (!test || locale === "en") return test;
  return { ...test, questions: (test.questions || []).map((question) => localizeQuestion(question, locale)) };
}
